// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLD_BE.Models;

#nullable disable

namespace QLD_BE.Migrations
{
    [DbContext(typeof(QldsvContext))]
    [Migration("20231215181911_QLDiem")]
    partial class QLDiem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLD_BE.Models.Account", b =>
                {
                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhanQuyen")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Login", "Pass")
                        .HasName("PK_Account_1");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.Diem", b =>
                {
                    b.Property<int>("Idd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idd"));

                    b.Property<int?>("DiemCc")
                        .HasColumnType("int")
                        .HasColumnName("DiemCC");

                    b.Property<int?>("DiemCuoiKy")
                        .HasColumnType("int");

                    b.Property<int?>("DiemLan1")
                        .HasColumnType("int");

                    b.Property<int?>("DiemLan2")
                        .HasColumnType("int");

                    b.Property<int?>("DiemTb")
                        .HasColumnType("int")
                        .HasColumnName("DiemTB");

                    b.Property<int?>("Idh")
                        .HasColumnType("int")
                        .HasColumnName("IDH");

                    b.Property<int?>("Idn")
                        .HasColumnType("int")
                        .HasColumnName("IDN");

                    b.Property<int?>("Idsv")
                        .HasColumnType("int")
                        .HasColumnName("IDSV");

                    b.HasKey("Idd");

                    b.HasIndex("Idh");

                    b.HasIndex("Idn");

                    b.HasIndex("Idsv");

                    b.ToTable("Diem", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.GiaoVien", b =>
                {
                    b.Property<int>("Idgv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDGV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idgv"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenGv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenGV");

                    b.HasKey("Idgv");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.HocPhan", b =>
                {
                    b.Property<int>("Idh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idh"));

                    b.Property<int?>("Idgv")
                        .HasColumnType("int")
                        .HasColumnName("IDGV");

                    b.Property<int?>("SoTc")
                        .HasColumnType("int")
                        .HasColumnName("SoTC");

                    b.Property<string>("TenHp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHP");

                    b.HasKey("Idh");

                    b.HasIndex("Idgv");

                    b.ToTable("HocPhan", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.Khoa", b =>
                {
                    b.Property<int>("Idk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idk"));

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idk");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.Lop", b =>
                {
                    b.Property<int>("Idl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idl"));

                    b.Property<int?>("Idk")
                        .HasColumnType("int")
                        .HasColumnName("IDK");

                    b.Property<string>("TenLop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Idl");

                    b.HasIndex("Idk");

                    b.ToTable("Lop", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.NamHoc", b =>
                {
                    b.Property<int>("Idn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idn"));

                    b.Property<int?>("NamHoc1")
                        .HasColumnType("int")
                        .HasColumnName("NamHoc");

                    b.HasKey("Idn");

                    b.ToTable("NamHoc", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.SinhVien", b =>
                {
                    b.Property<int>("Idsv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDSV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsv"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Idl")
                        .HasColumnType("int")
                        .HasColumnName("IDL");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("Idsv");

                    b.HasIndex("Idl");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("QLD_BE.Models.Diem", b =>
                {
                    b.HasOne("QLD_BE.Models.HocPhan", "IdhNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("Idh")
                        .HasConstraintName("FK_Diem_HocPhan");

                    b.HasOne("QLD_BE.Models.NamHoc", "IdnNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("Idn")
                        .HasConstraintName("FK_Diem_NamHoc");

                    b.HasOne("QLD_BE.Models.SinhVien", "IdsvNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("Idsv")
                        .HasConstraintName("FK_Diem_SinhVien");

                    b.Navigation("IdhNavigation");

                    b.Navigation("IdnNavigation");

                    b.Navigation("IdsvNavigation");
                });

            modelBuilder.Entity("QLD_BE.Models.HocPhan", b =>
                {
                    b.HasOne("QLD_BE.Models.GiaoVien", "IdgvNavigation")
                        .WithMany("HocPhans")
                        .HasForeignKey("Idgv")
                        .HasConstraintName("FK_HocPhan_GiaoVien");

                    b.Navigation("IdgvNavigation");
                });

            modelBuilder.Entity("QLD_BE.Models.Lop", b =>
                {
                    b.HasOne("QLD_BE.Models.Khoa", "IdkNavigation")
                        .WithMany("Lops")
                        .HasForeignKey("Idk")
                        .HasConstraintName("FK_Lop_Khoa");

                    b.Navigation("IdkNavigation");
                });

            modelBuilder.Entity("QLD_BE.Models.SinhVien", b =>
                {
                    b.HasOne("QLD_BE.Models.Lop", "IdlNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("Idl")
                        .HasConstraintName("FK_SinhVien_Lop");

                    b.Navigation("IdlNavigation");
                });

            modelBuilder.Entity("QLD_BE.Models.GiaoVien", b =>
                {
                    b.Navigation("HocPhans");
                });

            modelBuilder.Entity("QLD_BE.Models.HocPhan", b =>
                {
                    b.Navigation("Diems");
                });

            modelBuilder.Entity("QLD_BE.Models.Khoa", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("QLD_BE.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QLD_BE.Models.NamHoc", b =>
                {
                    b.Navigation("Diems");
                });

            modelBuilder.Entity("QLD_BE.Models.SinhVien", b =>
                {
                    b.Navigation("Diems");
                });
#pragma warning restore 612, 618
        }
    }
}
